### ISSUE TITLE
performance mismatch : newly trained model for 'tps' 

### ISSUE THREAD

**Issue by InnovArul** [ignacio-rocco/cnngeometric_pytorch#1]
Hi,

Thanks for sharing the code!

I would like to get a clarification regarding the performance mismatch during testing(eval_pf.py).
When tested with models from github, the performance is as below:

PCK affine: 0.4584
**PCK tps: 0.5157**
PCK affine+tps: 0.5702

When tested with models created using new training run (10 epochs), the performance is as below;

PCK affine: 0.4584
**PCK tps: 0.4215**
PCK affine+tps: 0.5634

I am not sure what is the reason for decrease in performance of 'tps'.
Am I missing some configurations?

**Comment by ignacio-rocco** [comment]
Hi, 

I believe the tps model which is online was trained with the Streetview-synth dataset and not with Pascal-synth. 

But let me train a tps model from scratch and check.

**Comment by InnovArul** [comment]
Thanks for the prompt response!
Could you please give any info whether this dataset (Tokyo Time Machine) available in public domain?

**Comment by ignacio-rocco** [comment]
Hi, I confirm these models were trained on Streetview-synth. This dataset is not publicly available, but is rather available on request to the author of http://www.di.ens.fr/willow/research/netvlad/ .

**Comment by ignacio-rocco** [comment]
Hi, in the latest commit I add newly trained models on Streetview-synth and Pascal-synth

**Comment by InnovArul** [comment]
Thank you very much for the clarifications and new models! I will try them.
