### ISSUE TITLE
Training with affine AND TPS

### ISSUE THREAD

**Issue by solitarysandman** [ignacio-rocco/cnngeometric_pytorch#13]
I have looked at the training code but I don't understand how you're using the affine warped output for TPS to get the final result. The code implies that you can train TPS separately and affine separately, but don't you need to both?

Am I missing something?

**Comment by thaithanhtuan** [comment]
> I have looked at the training code but I don't understand how you're using the affine warped output for TPS to get the final result. The code implies that you can train TPS separately and affine separately, but don't you need to both?
> 
> Am I missing something?

I think that each transformation has different advantages? If you apply affine first, then TPS, you would get better warped results.
May be affine transformation can give general shape of the target, but for more accurate in detail shape, TPS is better.
