### ISSUE TITLE
about test_pairs_pf.csv

### ISSUE THREAD

**Issue by zll152** [ignacio-rocco/cnngeometric_pytorch#2]
hi, when i run the demo.py, i can't download the  test_pairs_pf. csv. So where can i get the test_pairs_pf.csv? Thanks a lot

**Comment by ignacio-rocco** [comment]
Hi, the link http://www.di.ens.fr/willow/research/cnngeometric/other_resources/test_pairs_pf.csv is not working from your location?

**Comment by zll152** [comment]
thank you very much. U save my days. But what is the meaning of these values.
XA1 | XA2 | XA3 | XA4 | XA5 | XA6 | XA7 | XA8 | XA9 | XA10.......YB10
Meanwhile , i don't understand the train.csv (A22	A21	A12	A11	ty tx ) ,if i only want the Rotation and 
translation , how to set the values??

**Comment by ignacio-rocco** [comment]
Hi the values (A22	A21	A12	A11	ty tx ) correspond to the 2x2 affine transformation matrix, plus the translation vector:  [x',y']^T = [A11 A12;A21 A22] [x,y]^T + [tx,ty]^T

The values XAi, YAi, XBi, YBi correspond to the annotated points in the ProposalFlow dataset.

**Comment by zll152** [comment]
if i want use the weights trained on my data to test my picture for getting a result like you shows in the github, what should i do ?

**Comment by ignacio-rocco** [comment]
Hi, please see the newly added demo_notebook.ipynb.

**Comment by zll152** [comment]
Thanks a lot! U are a so kind man!!!

**Comment by zll152** [comment]
Hi，i think something wrong in demo_notebook.ipynb . In rotation only, I use the same model and weight, and the results he shows are always the opposite of the previous version of demo. For example, the correct result should be clockwise rotation of 30 degrees, the result of demo can be achieved, but his result is counterclockwise rotation of 30 degrees!

**Comment by zll152** [comment]
Hi，i think something wrong in demo_notebook.ipynb . In rotation only, I use the same model and weight, and the results he shows are always the opposite of the previous version of demo. For example, the correct result should be clockwise rotation of 30 degrees, the result of demo can be achieved, but his result is counterclockwise rotation of 30 degrees!@ignacio-rocco

**Comment by blair2020** [comment]
> thank you very much. U save my days. But what is the meaning of these values.
> XA1 | XA2 | XA3 | XA4 | XA5 | XA6 | XA7 | XA8 | XA9 | XA10.......YB10
> Meanwhile , i don't understand the train.csv (A22 A21 A12 A11 ty tx ) ,if i only want the Rotation and
> translation , how to set the values??

where is (A22 A21 A12 A11 ty tx )?
