### ISSUE TITLE
Some question about the model

### ISSUE THREAD

**Issue by KongCang** [ignacio-rocco/cnngeometric_pytorch#4]
1. Can you plot the model as a pdf document ?
2. In my match model the Xception works better than the  ResNet-101.
3. At last Thanks for your share.

**Comment by d-li14** [comment]
@KongCang Hi, Could you please specify how you load the pretrained Xception model in PyTorch, for it is not in the default model_zoo? And how about the performance gap in your experiments? Thanks in advance!
