### ISSUE TITLE
FileNotFoundError  trained_models/***.pth.tar

### ISSUE THREAD

**Issue by leoshine** [ignacio-rocco/cnngeometric_pytorch#5]
Creating CNN model...
Loading trained model weights...
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-9e711e2a0162> in <module>()
     13 print('Loading trained model weights...')
     14 if do_aff:
---> 15     checkpoint = torch.load(model_aff_path, map_location=lambda storage, loc: storage)
     16     checkpoint['state_dict'] = OrderedDict([(k.replace('vgg', 'model'), v) for k, v in checkpoint['state_dict'].items()])
     17     model_aff.load_state_dict(checkpoint['state_dict'])

~/anaconda3/lib/python3.6/site-packages/torch/serialization.py in load(f, map_location, pickle_module)
    257             (sys.version_info[0] == 3 and isinstance(f, pathlib.Path)):
    258         new_fd = True
--> 259         f = open(f, 'rb')
    260     try:
    261         return _load(f, map_location, pickle_module)

FileNotFoundError: [Errno 2] No such file or directory: 'trained_models/best_pascal_checkpoint_adam_affine_grid_loss_resnet_random.pth.tar'

**Comment by ignacio-rocco** [comment]
Hi, please see the Trained models section of Readme.md. You need to download the models yourself :)

**Comment by leoshine** [comment]
Oh Thanks.
