### ISSUE TITLE
Weights for the feature extractors?

### ISSUE THREAD

**Issue by mlopezantequera** [ignacio-rocco/cnngeometric_pytorch#6]
Hi! Thanks for publishing the code so quickly :+1: 

The pretrained models include weights only for the regressor, right? I'm assuming that one also needs to train the feature extractor to get better results. Is this the case, or have you found that training the extractor is not that relevant?

cheers

**Comment by Fromandto** [comment]
In my experiments, fine-tuning the feature extractor (on PASCAL) have negative impacts. This is reasonable as imagenet feature extractor is already very expressive.

**Comment by mlopezantequera** [comment]
Thanks for your answer. Was this also the case on tokyo street view?

**Comment by Fromandto** [comment]
I don't know but I assume so because Tokyo also lacks the diversity of ImageNet.

**Comment by ignacio-rocco** [comment]
Hi,
> The pretrained models include weights only for the regressor, right?

No, they are complete models which also include weights for the feature extractor, but this have not been finetuned, they are the same as in the ImageNet-pretrained feature extraction CNN.

Although we tried finetuning the feature extractor, we saw that, as @Fromandto  mentions it was not beneficial.

In a more recent work we try to overcome this, by finetuning using real image pairs:

http://www.di.ens.fr/willow/research/weakalign/
